### PR TITLE
Add launch argument to disable GUI start

### PR DESCRIPTION
**Pull request by safonas**
Add an argument to skip GUI launch and update the documentation

### CODE REVIEW

**Comment by safonas** [comment]
Yaay, my first public PR :man_dancing: 

I just wanted to enable the feature advertised in the documentation, namely

> This command starts the OpenTabletDriver daemon and, **if you choose to use it**, the GUI for configuring your tablet settings. 

It'll be useful for immutable distro I'm using, see https://universal-blue.discourse.group/t/my-huion-tablet-is-not-being-detected-on-kinoite-nvidia-custom-image/786/6

**Comment by jamesbt365** [comment]
Build failures are unrelated and I'll fix at some point soon.

Not sure I like how this is handled still, not sure how this ties into how flatpaks works but it would be neat if we could mirror the upstream behaviour if its viable.

The upstream packages do not autostart the daemon without the use of systemd (which I know isn't viable here) and currently running the desktop file keeps the driver running in the background indefinitely, which I suppose isn't ideal for some...

I understand that flatpaks handle stuff differently but I want to bring things in line with the upstream packaging as closely as possible in places like these, it should not be that much different to run OTD using the flatpak outside of the manual system-wide setup and the lack of a service.

Not sure the best approach here and this is why I haven't decoupled it yet.

**Comment by first-storm** [comment]
> Build failures are unrelated and I'll fix at some point soon.
> 
> Not sure I like how this is handled still, not sure how this ties into how flatpaks works but it would be neat if we could mirror the upstream behaviour if its viable.
> 
> The upstream packages do not autostart the daemon without the use of systemd (which I know isn't viable here) and currently running the desktop file keeps the driver running in the background indefinitely, which I suppose isn't ideal for some...
> 
> I understand that flatpaks handle stuff differently but I want to bring things in line with the upstream packaging as closely as possible in places like these, it should not be that much different to run OTD using the flatpak outside of the manual system-wide setup and the lack of a service.
> 
> Not sure the best approach here and this is why I haven't decoupled it yet.

There is an example called EasyEffects. You can check it on flathub.

**Comment by first-storm** [comment]
I've fixed the build failures. Just click "Update branch"

**Comment by first-storm** [comment]
I think it would be better if there is a option in the GUI to launch daemon on login.

**Comment by jamesbt365** [comment]
> I think it would be better if there is a option in the GUI to launch daemon on login.

Seems out of scope here, this PR already implements the required tooling for this, if anything we could add documentation on how to make a systemd service or simply just tell users to place a command in the startup of their DE/WM.

**Comment by safonas** [comment]
> we could add documentation on how to make a systemd service

good idea. I'll update the branch with systemd service howto and test this build shortly

**Comment by safonas** [comment]
@jamesbt365 @first-storm Apologies for spamming the thread with commits and builds here.

I've tested the build using systemd service and `-d` flag and it works flawlessly, please review.
opentabletdriver service

I've also added instructions on disabling kernel modules for immutable Fedora spins into manual doc section, not sure if this is relevant within this PR. Let me know if you want me to drop it.

**Review by jamesbt365 — APPROVED** [review]
Looks good, will merge for now.

**Pull request merged**
