### PR TITLE
Begin better documentation writeup

### PR DESCRIPTION
**Pull request by jamesbt365**
Currently this is nowhere near where I want it, just opening a pull request to a branch I made as I want to make my intentions clear. This PR should not be merged until for the most part it can help fix the key points of #22, however fully closing it in this PR is impossible due to the structure of this repository and its branches.

Suggestions are welcome.

Not to be merged until:
- [x] Split manual and automatic installs
- [x] Rewrite most sections and improve the general flow of the documentation.
- [x] Drop sudo of the execution of scripts
- [ ] Uninstallation instructions reimplemented

For future pull requests:
- Updating the scripts to make better sense
- adding new scripts for different installation methods
- reword the README.md, adding different sections, recommending the official packages where possible etc etc

Future plans as things stable may be to mirror this officially on https://opentabletdriver.net, but until things are stable here, the package will not be listed on our website.

### CODE REVIEW

**Comment by jamesbt365** [comment]
Can we prevent that from running on anything that doesn't target `master` or any other relevant branch?

**Comment by first-storm** [comment]
> Can we prevent that from running on anything that doesn't target `master` or any other relevant branch?

Okay. I will get it done in 2 weeks. (I am a high school student in China. I don't have much time.)

**Comment by jamesbt365** [comment]
> But could I keep "docs" branch?

I don't really have a problem with having docs and scripts split from the main repository. Not sure about anybody else, the intention here right now is to get everything into `docs-staging` then pull that into `docs` once its in a state I'm happy with.

**Comment by jamesbt365** [comment]
> Okay. I will get it done in 2 weeks. 

Opened #24 and assigned it to you.

**Comment by jamesbt365** [comment]
Apparently this is impossible, so i'll be combining `docs` and `scripts` into the main branches after the merge of this PR.

**Comment by jamesbt365** [comment]
Going to merge now and do a bit of reconfiguring on the way our repo is staged, we cannot realistically keep the docs and scripts branch, flathub just doesn't really provide anything allowing us to do that without seeing an error pop up every time.

I'm fine with having separate branches but there isn't really a practical advantage at this time, it just makes working on the docs, scripts and main flatpak files at the same time much more messy.

**Pull request merged**
